### ISSUE TITLE
Show count of duplicates and defer delete till toolbar icon is clicked

### ISSUE THREAD

**Issue by ghost** [nosoop/tab-deduper#15]
The notification pulls your attention away from the task at hand.  Would it be possible to add an icon, show the number of duplicate tabs  > 0, and defer the delete till when you click on toolbar icon?  The only cost of deferring the delete action is memory, but that's less valuable than the user's attention.

**Comment by nosoop** [comment]
Discovering and cleaning up duplicate tabs via addon button is a good idea.
However, it's also a completely different design from this addon, so I think it'd be better suited as its own thing.

**Comment by ghost** [comment]
No worries.
